import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import SidebarMenu from "@/components/layout/SidebarMenu";
import NavBar from "@/components/layout/NavBar";
import {BlockBusterBall} from "@/components/layout/BlockBusterBall";
import QueryProvider from "@/components/QueryProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.jpg",
    }
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <body className="h-screen w-screen flex">
        <SidebarMenu/>
        <BlockBusterBall/>


        {/* Main content */}
        <div className="flex-1 flex flex-col">
            <NavBar/>

            {/* Main Body */}
            <main className="flex-1 p-6 pl-24  overflow-auto">
                <QueryProvider>
                    {children}
                </QueryProvider>
            </main>
        </div>
        </body>
        </html>
    );
}
